spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:8100/iTrust2_test?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: root
    hikari:
      idleTimeout: 500
      connectionTimeout: 15000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

server:
  port: 8080
  servlet:
    contextPath: /iTrust2
